version: "3.1"

services:
  backend:
    container_name: julenque-backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/code
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        npm run dev --prefix backend
  frontend:
    tty: true
    environment:
      BACKEND_HOST: backend
      CHOKIDAR_USEPOLLING: "true"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: julenque-frontend
    restart: always
    depends_on:
        - backend
    links:
      - "backend:localhost"
    ports:
      - 3001:3001

    volumes:
      - /app/node_modules
      - ./frontend:/app

  nginx:
    image: nginx:1.13 # this will use the latest version of 1.13.x
    restart: unless-stopped
    container_name: julenque-nginx
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./cert:/etc/ssl
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"