const INITIAL_HEALTH = 6;
const ROUND_HEALTH_LOSS = 1;
const SOCKET_PORT = 5375;
const LOBBY_API_PORT = 5376;
const BOARDGAME_SERVER_PORT = 5377;
const BACKEND_PORT = 5378;
const FRONTEND_PORT = 5379;


module.exports = {INITIAL_HEALTH, ROUND_HEALTH_LOSS, SOCKET_PORT, LOBBY_API_PORT, BOARDGAME_SERVER_PORT, BACKEND_PORT, FRONTEND_PORT};
